# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link_to_article', models.URLField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Comleted'), (2, 'To review'), (3, 'Reviewed')], default=0)),
            ],
        ),
    ]
